In [26]:
import pandas as pd

df = pd.read_csv("./data/mass_case_description_train_set.csv")

In [4]:
# Number of rows and columns
df.shape

(1318, 14)

In [ ]:
# Dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1318 entries, 0 to 1317
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               1318 non-null   object
 1   breast_density           1318 non-null   int64
 2   left or right breast     1318 non-null   object
 3   image view               1318 non-null   object
 4   abnormality id           1318 non-null   int64
 5   abnormality type         1318 non-null   object
 6   mass shape               1314 non-null   object
 7   mass margins             1275 non-null   object
 8   assessment               1318 non-null   int64
 9   pathology                1318 non-null   object
 10  subtlety                 1318 non-null   int64
 11  image file path          1318 non-null   object
 12  cropped image file path  1318 non-null   object
 13  ROI mask file path       1318 non-null   object
dtypes: int64(4), object(10)
memory usage: 144.3+ KB

In [27]:
df["Label"] = df["pathology"].map({
    "MALIGNANT": 1,
    "BENIGN": 0,
    "BENIGN_WITHOUT_CALLBACK": 0,
})

In [28]:
df[["pathology", "Label"]].value_counts(dropna=False)

pathology                Label
MALIGNANT                1        637
BENIGN                   0        577
BENIGN_WITHOUT_CALLBACK  0        104
Name: count, dtype: int64

In [29]:
df[["Label"]].value_counts(dropna=False)

Label
0        681
1        637
Name: count, dtype: int64

In [9]:
df["folder"] = df["image file path"].str.split("/", n=1).str[0]

In [12]:
df["folder"]

0         Mass-Training_P_00001_LEFT_CC
1        Mass-Training_P_00001_LEFT_MLO
2         Mass-Training_P_00004_LEFT_CC
3        Mass-Training_P_00004_LEFT_MLO
4       Mass-Training_P_00004_RIGHT_MLO
                     ...
1313    Mass-Training_P_02033_RIGHT_MLO
1314     Mass-Training_P_02079_RIGHT_CC
1315    Mass-Training_P_02079_RIGHT_MLO
1316      Mass-Training_P_02092_LEFT_CC
1317     Mass-Training_P_02092_LEFT_MLO
Name: folder, Length: 1318, dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1318 entries, 0 to 1317
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               1318 non-null   object
 1   breast_density           1318 non-null   int64
 2   left or right breast     1318 non-null   object
 3   image view               1318 non-null   object
 4   abnormality id           1318 non-null   int64
 5   abnormality type         1318 non-null   object
 6   mass shape               1314 non-null   object
 7   mass margins             1275 non-null   object
 8   assessment               1318 non-null   int64
 9   pathology                1318 non-null   object
 10  subtlety                 1318 non-null   int64
 11  image file path          1318 non-null   object
 12  cropped image file path  1318 non-null   object
 13  ROI mask file path       1318 non-null   object
 14  Label                    1318 non-null   int64
 15  folder                   1318 non-null   object
dtypes: int64(5), object(11)
memory usage: 164.9+ KB

In [16]:
df[["image file path", "folder"]].head(10)

,image file path,folder
0,Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00001_LEFT_CC
1,Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00001_LEFT_MLO
2,Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...,Mass-Training_P_00004_LEFT_CC
3,Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00004_LEFT_MLO
4,Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00004_RIGHT_MLO
5,Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.959...,Mass-Training_P_00009_RIGHT_CC
6,Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00009_RIGHT_MLO
7,Mass-Training_P_00015_LEFT_MLO/1.3.6.1.4.1.959...,Mass-Training_P_00015_LEFT_MLO
8,Mass-Training_P_00018_RIGHT_CC/1.3.6.1.4.1.959...,Mass-Training_P_00018_RIGHT_CC
9,Mass-Training_P_00018_RIGHT_MLO/1.3.6.1.4.1.95...,Mass-Training_P_00018_RIGHT_MLO

In [18]:
df["study"] = df["image file path"].str.split("/").str[1].str[-5:]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1318 entries, 0 to 1317
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               1318 non-null   object
 1   breast_density           1318 non-null   int64
 2   left or right breast     1318 non-null   object
 3   image view               1318 non-null   object
 4   abnormality id           1318 non-null   int64
 5   abnormality type         1318 non-null   object
 6   mass shape               1314 non-null   object
 7   mass margins             1275 non-null   object
 8   assessment               1318 non-null   int64
 9   pathology                1318 non-null   object
 10  subtlety                 1318 non-null   int64
 11  image file path          1318 non-null   object
 12  cropped image file path  1318 non-null   object
 13  ROI mask file path       1318 non-null   object
 14  Label                    1318 non-null   int64
 15  folder                   1318 non-null   object
 16  study                    1318 non-null   object
dtypes: int64(5), object(12)
memory usage: 175.2+ KB

In [20]:
df[["image file path", "study"]].head(10)

                                     image file path  study
0  Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...  74994
1  Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...  90988
2  Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...  95697
3  Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...  20939
4  Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...  24486
5  Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.959...  71955
6  Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.95...  85525
7  Mass-Training_P_00015_LEFT_MLO/1.3.6.1.4.1.959...  66724
8  Mass-Training_P_00018_RIGHT_CC/1.3.6.1.4.1.959...  18937
9  Mass-Training_P_00018_RIGHT_MLO/1.3.6.1.4.1.95...  09956

In [21]:
df["series"] = df["image file path"].str.split("/").str[2].str[-5:]

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1318 entries, 0 to 1317
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               1318 non-null   object
 1   breast_density           1318 non-null   int64
 2   left or right breast     1318 non-null   object
 3   image view               1318 non-null   object
 4   abnormality id           1318 non-null   int64
 5   abnormality type         1318 non-null   object
 6   mass shape               1314 non-null   object
 7   mass margins             1275 non-null   object
 8   assessment               1318 non-null   int64
 9   pathology                1318 non-null   object
 10  subtlety                 1318 non-null   int64
 11  image file path          1318 non-null   object
 12  cropped image file path  1318 non-null   object
 13  ROI mask file path       1318 non-null   object
 14  Label                    1318 non-null   int64
dtypes: int64(5), object(10)
memory usage: 154.6+ KB

In [23]:
df[["image file path", "study", "series"]].head(10)

                                     image file path  study series
0  Mass-Training_P_00001_LEFT_CC/1.3.6.1.4.1.9590...  74994  24515
1  Mass-Training_P_00001_LEFT_MLO/1.3.6.1.4.1.959...  90988  80834
2  Mass-Training_P_00004_LEFT_CC/1.3.6.1.4.1.9590...  95697  46540
3  Mass-Training_P_00004_LEFT_MLO/1.3.6.1.4.1.959...  20939  00162
4  Mass-Training_P_00004_RIGHT_MLO/1.3.6.1.4.1.95...  24486  89890
5  Mass-Training_P_00009_RIGHT_CC/1.3.6.1.4.1.959...  71955  15839
6  Mass-Training_P_00009_RIGHT_MLO/1.3.6.1.4.1.95...  85525  55201
7  Mass-Training_P_00015_LEFT_MLO/1.3.6.1.4.1.959...  66724  63688
8  Mass-Training_P_00018_RIGHT_CC/1.3.6.1.4.1.959...  18937  64601
9  Mass-Training_P_00018_RIGHT_MLO/1.3.6.1.4.1.95...  09956  65391

In [ ]:
source_root / row["folder"] / row["study"] / row["series"]

In [26]:
import glob
files = glob.glob(str(samples_dir / "*.dcm"))
print(files)

['data/samples/2_dc68e89e-c200-4acf-9e85-556cf235bc3a.dcm', 'data/samples/4_85ca964f-d307-4bbb-b94c-960272fd8a9d.dcm', 'data/samples/6_7597b07a-abe7-4486-bc7e-cd8ad9446a62.dcm', 'data/samples/0_e35e53fd-5312-406e-ad9f-4c11e725e53f.dcm', 'data/samples/5_54e34524-3485-44c2-8d14-47c82eb220cc.dcm', 'data/samples/1_f4e98158-2795-460e-8037-b68e72d55477.dcm', 'data/samples/3_34d9ef1e-6514-4438-b0a8-9b994143fa8d.dcm', 'data/samples/7_10976292-299b-40d2-90a6-d30bbefbb991.dcm']

In [5]:
from pathlib import Path
source_root = Path(
    "/Volumes/Samsung_T7/Not_Sync/CBIS-DDSM-All-doiJNLP-zzWs5zfZ/cbis_ddsm")

print(source_root.exists())


samples_dir = Path("./data/samples")
samples_dir.absolute()

True

PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples')

In [6]:
from pathlib import Path
print(Path.cwd())
print(Path.home())

/Users/helmutremse/tempMini/23_final_3070/code/DDSM
/Users/helmutremse

In [7]:
Path.home()

PosixPath('/Users/helmutremse')

In [24]:
mypath = Path.cwd() / "data" / "samples"
print(mypath)
mypath.glob("*.dcm")
myfiles = list(mypath.glob("*.dcm"))
print(sorted(myfiles))
print(sorted(myfiles)[0])
print(sorted(myfiles)[1])

/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples
[PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/0_e35e53fd-5312-406e-ad9f-4c11e725e53f.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/1_f4e98158-2795-460e-8037-b68e72d55477.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/2_dc68e89e-c200-4acf-9e85-556cf235bc3a.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/3_34d9ef1e-6514-4438-b0a8-9b994143fa8d.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/4_85ca964f-d307-4bbb-b94c-960272fd8a9d.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/5_54e34524-3485-44c2-8d14-47c82eb220cc.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/6_7597b07a-abe7-4486-bc7e-cd8ad9446a62.dcm'), PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/7_10976292-299b-40d2-90a6-d30bbefbb991.dcm')]
/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/0_e35e53fd-5312-406e-ad9f-4c11e725e53f.dcm
/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples/1_f4e98158-2795-460e-8037-b68e72d55477.dcm

In [23]:
mypath = Path.cwd().joinpath("data", "samples")
mypath

PosixPath('/Users/helmutremse/tempMini/23_final_3070/code/DDSM/data/samples')

In [34]:
from pathlib import Path
samples_dir = Path("./data/samples")
source_root = Path(
    "/Volumes/Samsung_T7/Not_Sync/CBIS-DDSM-All-doiJNLP-zzWs5zfZ/cbis_ddsm")

for i, row in df.head(8).iterrows():
    series_path = source_root / row["folder"] / row["study"] / row["series"]
    print(series_path)

KeyError: 'folder'

In [ ]:
from pathlib import Path
import shutil

source_root = Path(
    "/Volumes/Samsung_T7/Not_Sync/CBIS-DDSM-All-doiJNLP-zzWs5zfZ/cbis_ddsm"
)
samples_dir = Path("./data/samples")
# If exist_ok=True, FileExistsError isn't raised for an existent path.
# If parents=True, the path with a target directory and one or more non-existent parent directories can be created, not getting FileNotFoundError.
# Basically, True is set to it
# parents=True: Creates all missing parent folders automatically.
# exist_ok=True: Prevents Python from crashing if the folder already exists
samples_dir.mkdir(parents=True, exist_ok=True)

# Use the first 8 dataframe rows
for i, row in df.head(8).iterrows():
    # / is considered an concatenation operator for Path objects, which allows you to concatenate paths in a more readable way.
    series_path = source_root / row["folder"] / row["study"] / row["series"]

    # Each series folder contains one DICOM file
    dicom_file = next(series_path.glob("*.dcm"), None)

    if dicom_file is None:
        print(f"No DICOM file found: {series_path}")
        continue

    # Prefix with row index to prevent filename collisions
    destination = samples_dir / f"{i}_{dicom_file.name}"
    shutil.copy2(dicom_file, destination)

print("Done.")

Done.